import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { EXTRA_SEALED, readBlocked, readLimits, readPrelude } from "./sandboxSource.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "../../..");
const source = resolve(root, "crates/core/src/script.rs");
const outDir = resolve(here, "public");
const outFile = resolve(outDir, "script-worker.js");
const limitsFile = resolve(here, "limits.generated.ts");
const scanSource = resolve(root, "crates/core/src/scan.rs");
const scanFile = resolve(here, "scanRules.generated.ts");

const rust = readFileSync(source, "utf8");
const prelude = readPrelude(rust, source);
const blocked = readBlocked(rust, source);
const limits = readLimits(rust, source);

const worker = `// GENERATED by src/lib/web/gen-worker.mjs from crates/core/src/script.rs — do not edit.
// The pm.* prelude below is byte-identical to the one the desktop app runs in QuickJS.
"use strict";

var PRELUDE = ${JSON.stringify(prelude)};
var BLOCKED = ${JSON.stringify(blocked)};
var EXTRA_BLOCKED = ${JSON.stringify(EXTRA_SEALED)};

function trap(name, why) {
  try {
    Object.defineProperty(globalThis, name, {
      configurable: true,
      get: function () {
        throw new Error(name + " is not available in M\\u00e1ndalo scripts: " + why);
      },
    });
  } catch (e) {
    /* a non-configurable global cannot be trapped; nothing to do */
  }
}

function seal() {
  for (var i = 0; i < BLOCKED.length; i++) trap(BLOCKED[i][0], BLOCKED[i][1]);
  for (var j = 0; j < EXTRA_BLOCKED.length; j++) trap(EXTRA_BLOCKED[j][0], EXTRA_BLOCKED[j][1]);
}

// A dynamic import is a keyword form, so no global can be trapped to stop it. QuickJS
// has no module loader at all, which is the behaviour this reproduces: the source is
// refused before it runs rather than being allowed to reach the network.
var DYNAMIC_IMPORT = /(^|[^.\\w$])import\\s*(\\(|\\.)/;

function refuseDynamicImport(source) {
  if (DYNAMIC_IMPORT.test(source)) {
    throw new Error(
      "import() is not available in M\\u00e1ndalo scripts: there is no module loader; scripts cannot import code",
    );
  }
}

var reply = self.postMessage.bind(self);

self.onmessage = function (event) {
  var payload = event.data;
  seal();
  try {
    refuseDynamicImport(payload.source);
    globalThis.__ctx_json = JSON.stringify(payload.context);
    (0, eval)(PRELUDE);
    (0, eval)(payload.source);
    reply({ ok: true, outcome: JSON.parse(globalThis.__mandalo.outcome()) });
  } catch (e) {
    reply({ ok: false, error: e && e.message ? String(e.message) : String(e) });
  }
};
`;

const limitsSource = `// GENERATED by src/lib/web/gen-worker.mjs from crates/core/src/script.rs — do not edit.
// The desktop app enforces both of these on QuickJS; the browser can only enforce the
// timeout, so a script that outgrows the memory budget is reported, not prevented.
export const LIMITS = { memoryBytes: ${limits.memoryBytes}, timeoutMs: ${limits.timeoutMs} } as const;
`;

// The named credential patterns, lifted from the Rust scanner so the browser
// cannot quietly fall behind it. Only these are portable: the entropy and
// encoded-payload guesses around them need Rust, and the review says so rather
// than implying the browser looked as hard.
function readScanRules(source, path) {
  const block = source.match(/\[\n([\s\S]*?)\n\s*\]\n\s*\.into_iter\(\)/);
  if (!block) throw new Error(`no rule table found in ${path}`);
  const rules = [];
  const entry = /\(\s*"([a-z0-9-]+)",\s*r"((?:[^"\\]|\\.)*)",?\s*\)/g;
  let found;
  while ((found = entry.exec(block[1])) !== null) rules.push([found[1], found[2]]);
  if (rules.length === 0) throw new Error(`no rules parsed out of ${path}`);
  return rules;
}

const scanRules = readScanRules(readFileSync(scanSource, "utf8"), scanSource);
const scanRulesSource = `// GENERATED by src/lib/web/gen-worker.mjs from crates/core/src/scan.rs — do not edit.
// The named credential patterns only. The desktop scanner also weighs entropy and
// decodes base64 payloads, which is why a review taken in the browser says which
// of the two ran.
export const SCAN_RULES: readonly (readonly [string, string])[] = [
${scanRules.map(([name, pattern]) => `  [${JSON.stringify(name)}, ${JSON.stringify(pattern)}],`).join("\n")}
];
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(scanFile, scanRulesSource, "utf8");
writeFileSync(outFile, worker, "utf8");
writeFileSync(limitsFile, limitsSource, "utf8");
process.stdout.write(
  `script worker: ${prelude.length} bytes of prelude, ${blocked.length + EXTRA_SEALED.length} ` +
    `sealed globals, ${limits.timeoutMs}ms / ${limits.memoryBytes}B limits, ` +
    `${scanRules.length} scan rules -> ${outFile}\n`,
);
