import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "../../..");
const source = resolve(root, "crates/core/src/script.rs");
const outDir = resolve(here, "public");
const outFile = resolve(outDir, "script-worker.js");

const rust = readFileSync(source, "utf8");
const open = 'const PRELUDE: &str = r#"';
const start = rust.indexOf(open);
if (start === -1) throw new Error(`PRELUDE not found in ${source}`);
const from = start + open.length;
const end = rust.indexOf('"#;', from);
if (end === -1) throw new Error(`unterminated PRELUDE raw string in ${source}`);
const prelude = rust.slice(from, end);

const blockedStart = rust.indexOf("const BLOCKED_GLOBALS: &[(&str, &str)] = &[");
const blockedEnd = rust.indexOf("];", blockedStart);
const blocked = [
  ...rust
    .slice(blockedStart, blockedEnd)
    .matchAll(/"([A-Za-z]+)"\s*,\s*(?:\n\s*)?"((?:[^"\\]|\\.)*)"/g),
].map(([, name, why]) => [name, why.replace(/\\"/g, '"')]);
if (blocked.length === 0)
  throw new Error(`BLOCKED_GLOBALS not found in ${source}`);

const worker = `// GENERATED by src/lib/web/gen-worker.mjs from crates/core/src/script.rs — do not edit.
// The pm.* prelude below is byte-identical to the one the desktop app runs in QuickJS.
"use strict";

var PRELUDE = ${JSON.stringify(prelude)};
var BLOCKED = ${JSON.stringify(blocked)};

function seal() {
  for (var i = 0; i < BLOCKED.length; i++) {
    (function (name, why) {
      try {
        Object.defineProperty(globalThis, name, {
          configurable: true,
          get: function () {
            throw new Error(name + " is not available in Mándalo scripts: " + why);
          },
        });
      } catch (e) {
        /* a non-configurable global cannot be trapped; nothing to do */
      }
    })(BLOCKED[i][0], BLOCKED[i][1]);
  }
  var extra = [
    ["importScripts", "scripts cannot import code"],
    ["Worker", "scripts have no host runtime access"],
    ["SharedWorker", "scripts have no host runtime access"],
    ["EventSource", "scripts cannot make network requests"],
    ["indexedDB", "scripts have no persistent storage"],
    ["caches", "scripts have no persistent storage"],
    ["sessionStorage", "scripts have no persistent storage"],
    ["navigator", "scripts have no host runtime access"],
    ["self", "scripts do not run in a browser"],
    ["postMessage", "scripts cannot make network requests"],
  ];
  for (var j = 0; j < extra.length; j++) {
    (function (name, why) {
      try {
        Object.defineProperty(globalThis, name, {
          configurable: true,
          get: function () {
            throw new Error(name + " is not available in Mándalo scripts: " + why);
          },
        });
      } catch (e) {
        /* see above */
      }
    })(extra[j][0], extra[j][1]);
  }
}

var reply = self.postMessage.bind(self);

self.onmessage = function (event) {
  var payload = event.data;
  seal();
  try {
    globalThis.__ctx_json = JSON.stringify(payload.context);
    (0, eval)(PRELUDE);
    (0, eval)(payload.source);
    reply({ ok: true, outcome: JSON.parse(globalThis.__mandalo.outcome()) });
  } catch (e) {
    reply({ ok: false, error: e && e.message ? String(e.message) : String(e) });
  }
};
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, worker, "utf8");
process.stdout.write(
  `script worker: ${prelude.length} bytes of prelude, ${blocked.length} blocked globals -> ${outFile}\n`,
);
