// GENERATED by src/lib/web/gen-worker.mjs from crates/core/src/script.rs — do not edit.
// The desktop app enforces both of these on QuickJS; the browser can only enforce the
// timeout, so a script that outgrows the memory budget is reported, not prevented.
export const LIMITS = { memoryBytes: 33554432, timeoutMs: 2000 } as const;
