// GENERATED by src/lib/web/gen-worker.mjs from crates/core/src/scan.rs — do not edit.
// The named credential patterns only. The desktop scanner also weighs entropy and
// decodes base64 payloads, which is why a review taken in the browser says which
// of the two ran.
export const SCAN_RULES: readonly (readonly [string, string])[] = [
  ["jwt", "eyJ[A-Za-z0-9_-]{8,}\\.[A-Za-z0-9_-]{8,}\\.[A-Za-z0-9_-]{8,}"],
  ["stripe-live-key", "sk_live_[0-9A-Za-z]{10,}"],
  ["github-token", "gh[pousr]_[0-9A-Za-z]{20,}"],
  ["aws-access-key", "(AKIA|ASIA|ABIA|ACCA)[0-9A-Z]{16}"],
  ["google-api-key", "AIza[0-9A-Za-z_\\-]{35}"],
  ["private-key", "-----BEGIN [A-Z ]*PRIVATE KEY-----"],
  ["gitlab-token", "glpat-[0-9A-Za-z_\\-]{20,}"],
  ["slack-token", "xox[baprs]-[0-9A-Za-z\\-]{10,}"],
  ["npm-token", "npm_[0-9A-Za-z]{36}"],
  ["anthropic-key", "sk-ant-[0-9A-Za-z_\\-]{20,}"],
  ["openai-key", "sk-proj-[0-9A-Za-z_\\-]{20,}"],
  ["credential-in-url", "[a-zA-Z][a-zA-Z0-9+.\\-]*://[^/\\s:@]+:[^/\\s@]{6,}@"],
  ["base32-token", "[A-Z2-7]{32,}={0,6}"],
];
