import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../..");
const source = resolve(repoRoot, "crates/core/src/script.rs");
const outFile = resolve(here, "../src/engine/prelude.generated.ts");

const rust = readFileSync(source, "utf8");

function extractPrelude() {
  const open = 'const PRELUDE: &str = r#"';
  const start = rust.indexOf(open);
  if (start === -1) throw new Error(`PRELUDE not found in ${source}`);
  const from = start + open.length;
  const end = rust.indexOf('"#;', from);
  if (end === -1) throw new Error(`unterminated PRELUDE raw string in ${source}`);
  return rust.slice(from, end);
}

function extractBlocked() {
  const start = rust.indexOf("const BLOCKED_GLOBALS: &[(&str, &str)] = &[");
  if (start === -1) throw new Error(`BLOCKED_GLOBALS not found in ${source}`);
  const end = rust.indexOf("];", start);
  const entries = [
    ...rust
      .slice(start, end)
      .matchAll(/"([A-Za-z]+)"\s*,\s*(?:\n\s*)?"((?:[^"\\]|\\.)*)"/g),
  ].map(([, name, why]) => [name, why.replace(/\\"/g, '"')]);
  if (entries.length === 0) throw new Error(`BLOCKED_GLOBALS is empty in ${source}`);
  return entries;
}

function extractLimits() {
  const start = rust.indexOf("impl Default for Limits");
  if (start === -1) throw new Error(`Limits default not found in ${source}`);
  const block = rust.slice(start, rust.indexOf("}\n}", start));
  const memory = /memory_bytes:\s*([0-9*\s]+),/.exec(block);
  const timeout = /timeout_ms:\s*([0-9]+),/.exec(block);
  if (!memory || !timeout) throw new Error(`could not read Limits defaults from ${source}`);
  const bytes = memory[1]
    .split("*")
    .map((part) => Number(part.trim()))
    .reduce((a, b) => a * b, 1);
  return { memoryBytes: bytes, timeoutMs: Number(timeout[1]) };
}

const prelude = extractPrelude();
const blocked = extractBlocked();
const limits = extractLimits();

const banner =
  "// GENERATED by scripts/gen-prelude.mjs from crates/core/src/script.rs — do not edit.\n" +
  "// The prelude below is byte-identical to the one the Rust engine runs in QuickJS;\n" +
  "// regenerate and commit whenever crates/core/src/script.rs changes.\n";

const workerHarness = `
var reply = parentPort.postMessage.bind(parentPort);

function seal() {
  for (var i = 0; i < BLOCKED.length; i++) trap(BLOCKED[i][0], BLOCKED[i][1]);
  for (var j = 0; j < EXTRA_BLOCKED.length; j++) trap(EXTRA_BLOCKED[j][0], EXTRA_BLOCKED[j][1]);
}

function trap(name, why) {
  try {
    Object.defineProperty(globalThis, name, {
      configurable: true,
      get: function () {
        throw new Error(name + " is not available in M\\u00e1ndalo scripts: " + why);
      },
    });
  } catch (e) {
    void e;
  }
}

parentPort.once("message", function (payload) {
  seal();
  try {
    globalThis.__ctx_json = JSON.stringify(payload.context);
    (0, eval)(PRELUDE);
    (0, eval)(payload.source);
    reply({ ok: true, outcome: JSON.parse(globalThis.__mandalo.outcome()) });
  } catch (e) {
    reply({ ok: false, error: e && e.message ? String(e.message) : String(e) });
  }
});
`;

// Node exposes reach that QuickJS simply does not have, so the seal has to be wider than
// BLOCKED_GLOBALS. It stays limited to names that grant host access: trapping a harmless
// global would only make `typeof` throw where the Rust engine answers "undefined".
const extra = [
  ["importScripts", "scripts cannot import code"],
  ["Worker", "scripts have no host runtime access"],
  ["SharedWorker", "scripts have no host runtime access"],
  ["EventSource", "scripts cannot make network requests"],
  ["indexedDB", "scripts have no persistent storage"],
  ["caches", "scripts have no persistent storage"],
  ["sessionStorage", "scripts have no persistent storage"],
  ["navigator", "scripts have no host runtime access"],
  ["self", "scripts do not run in a browser"],
  ["postMessage", "scripts cannot make network requests"],
  ["parentPort", "scripts have no host runtime access"],
  ["MessageChannel", "scripts have no host runtime access"],
  ["MessagePort", "scripts have no host runtime access"],
  ["BroadcastChannel", "scripts cannot make network requests"],
  ["WebAssembly", "scripts cannot import code"],
];

const out = `${banner}
export const PRELUDE = ${JSON.stringify(prelude)};

export const BLOCKED_GLOBALS: readonly (readonly [string, string])[] = ${JSON.stringify(blocked)};

export const LIMITS = { memoryBytes: ${limits.memoryBytes}, timeoutMs: ${limits.timeoutMs} } as const;

export const WORKER_SOURCE = [
  '"use strict";',
  'const { parentPort } = require("node:worker_threads");',
  "var PRELUDE = " + JSON.stringify(PRELUDE) + ";",
  "var BLOCKED = " + JSON.stringify(BLOCKED_GLOBALS) + ";",
  "var EXTRA_BLOCKED = " + JSON.stringify(${JSON.stringify(extra)}) + ";",
  ${JSON.stringify(workerHarness)},
].join("\\n");
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, out, "utf8");
process.stdout.write(
  `prelude: ${prelude.length} bytes, ${blocked.length} blocked globals, ` +
    `${limits.timeoutMs}ms / ${limits.memoryBytes}B limits -> ${outFile}\n`,
);
