import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  EXTRA_SEALED,
  readBlocked,
  readLimits,
  readPrelude,
} from "../../src/lib/web/sandboxSource.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../..");
const source = resolve(repoRoot, "crates/core/src/script.rs");
const outFile = resolve(here, "../src/engine/prelude.generated.ts");

const rust = readFileSync(source, "utf8");

const prelude = readPrelude(rust, source);
const blocked = readBlocked(rust, source);
const limits = readLimits(rust, source);

const banner =
  "// GENERATED by scripts/gen-prelude.mjs from crates/core/src/script.rs — do not edit.\n" +
  "// The prelude below is byte-identical to the one the Rust engine runs in QuickJS;\n" +
  "// regenerate and commit whenever crates/core/src/script.rs changes.\n";

const workerHarness = `
var reply = parentPort.postMessage.bind(parentPort);

function seal() {
  for (var i = 0; i < BLOCKED.length; i++) trap(BLOCKED[i][0], BLOCKED[i][1]);
  for (var j = 0; j < EXTRA_BLOCKED.length; j++) trap(EXTRA_BLOCKED[j][0], EXTRA_BLOCKED[j][1]);
}

function trap(name, why) {
  try {
    Object.defineProperty(globalThis, name, {
      configurable: true,
      get: function () {
        throw new Error(name + " is not available in M\\u00e1ndalo scripts: " + why);
      },
    });
  } catch (e) {
    void e;
  }
}

var DYNAMIC_IMPORT = /(^|[^.\\w$])import\\s*(\\(|\\.)/;

function refuseDynamicImport(source) {
  if (DYNAMIC_IMPORT.test(source)) {
    throw new Error(
      "import() is not available in M\\u00e1ndalo scripts: there is no module loader; scripts cannot import code",
    );
  }
}

parentPort.once("message", function (payload) {
  seal();
  try {
    refuseDynamicImport(payload.source);
    globalThis.__ctx_json = JSON.stringify(payload.context);
    (0, eval)(PRELUDE);
    (0, eval)(payload.source);
    reply({ ok: true, outcome: JSON.parse(globalThis.__mandalo.outcome()) });
  } catch (e) {
    reply({ ok: false, error: e && e.message ? String(e.message) : String(e) });
  }
});
`;

const out = `${banner}
export const PRELUDE = ${JSON.stringify(prelude)};

export const BLOCKED_GLOBALS: readonly (readonly [string, string])[] = ${JSON.stringify(blocked)};

export const LIMITS = { memoryBytes: ${limits.memoryBytes}, timeoutMs: ${limits.timeoutMs} } as const;

export const WORKER_SOURCE = [
  '"use strict";',
  'const { parentPort } = require("node:worker_threads");',
  "var PRELUDE = " + JSON.stringify(PRELUDE) + ";",
  "var BLOCKED = " + JSON.stringify(BLOCKED_GLOBALS) + ";",
  "var EXTRA_BLOCKED = " + JSON.stringify(${JSON.stringify(EXTRA_SEALED)}) + ";",
  ${JSON.stringify(workerHarness)},
].join("\\n");
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, out, "utf8");
process.stdout.write(
  `prelude: ${prelude.length} bytes, ${blocked.length} blocked globals, ` +
    `${limits.timeoutMs}ms / ${limits.memoryBytes}B limits -> ${outFile}\n`,
);
